ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: weather.local
      paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
              name: weather
              port:
                number: 80
  tls: []

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
